### ISSUE TITLE
Falcor?

### ISSUE THREAD

**Issue by a9a4k** [jas-chen/thisless-react#2]
Could you please add a falcor to the stack. Really interested on how it will play out. I am trying currently to make a simple todo app, but my implementation seems weird. Or can you give directions on how you would go about adding falcor to your example and I will go from there?

**Comment by jas-chen** [comment]
@almasakchabayev I know nothing about falcor, sorry for that!

**Comment by a9a4k** [comment]
@jas-chen It's ok :) Check it out though! I think it will fit quite nicely to what you have

**Comment by jas-chen** [comment]
Ok, thank you!
