### ISSUE TITLE
Separation of concerns with Events/Views

### ISSUE THREAD

**Issue by davesnx** [jas-chen/thisless-react#3]
Hello @jas-chen,

I was following your really good attempts to join RxJS with Redux or at least the Flux way (like having one data way/actions as a objects/etc...) and I tried it and isn't a easy task. Really like it.

Mainly I was reading 4 months ago, your first approach [jas-chen/rx-redux](https://github.com/jas-chen/rx-redux) but this time I found more reasonable but with a major issue that can I want to discuss a little bit.

The separation between the _Component_ and the _Model/Presenter_ must be clear for reuse the components and for keep smart the comunication between components.

I found 2 issues with the implementation and could be easy to solve:

In the counter example you found the `getActionStream` that is exactly the idea of a Presenter in a [MVP pattern](http://stackoverflow.com/a/101561). 
https://github.com/jas-chen/rx-redux/blob/master/examples/counter-rx/view/index.js

and in the TodoMVC example, you are passing the events subscription into the `container` and it's also another breaking layers.
https://github.com/jas-chen/thisless-react/blob/master/examples/todomvc/index.js

What I want to discuss and later implement (or at least try it):
- The components should receive the events and the props, the onClick handlers or any UI interaction should call the proper event that is a clousure, passing the additional properties, basically reimplement bindActionCreators.
- Inside the store, create a subscription on the store with the actions$, with a merge and a `mapTo`, and this would be the `connect` method that redux have. and then we will have the possibility of subscribe on a changes on the state$ and render the component o pass the properties into a dump component.

This would create the idea of MVP or (IMV as Cycle.js say) with Reactive Programing and React.

What do you think?
I will try to update this Issue with some snippets for make more clear the interfaces.

Pd. Feel free to revoke whatever idea to implement or simply that doesn't sound correct to you.
Really apreciate your work!

Thanks!

**Comment by jas-chen** [comment]
Hi @davesnx,

Thanks for opening this issue, I'am trying to catch your points but not sure if I get them right, really need some snippets!

**Comment by davesnx** [comment]
What about this stuff (I just begin today getting this repo): https://github.com/davesnx/rxduce

**Comment by jas-chen** [comment]
In thisless react, the design is like this

```
           +---------+
  intent$  |         |  state$
+--------> |  Store  +---------->
           |         |
           +---------+


                          element
           +---------+   +------>
  props    |         |   |
+--------> |Component+---+
 (state$,  |         |   |
  event$)  +---------+   +------>
                          event$


           +---------+
  event$   |         |  intent$
+--------> |  Handle +---------->
           |         |
           +---------+

```

A component receives event streams from other components, and will observe them, this is the MVI architecture described in Cycle.js. Components are reusable and testable.

I don't think passing event streams as callback functions into a component is a good idea, developers have to create that particular event streams every time to use a component?

Also, passing store into components is not reactive IMO, that makes components dependent on particular Model implementation. In thisless-react, Model is abstract, it just a state stream provider, you can replace redux without any problem.

Please tell me if I misunderstood anything :-)

**Comment by davesnx** [comment]
Yeah, the idea of passing the store in a component isn't reactive, but in this case the component is a container it's based on the idea of redux that a container can be able to listen the store.

The component that have some interaction with the streams, needs the events as a definition of this component. 

What I don't like is that the component serve the events$, should be the container how says which events$ have in this component.

**Comment by jas-chen** [comment]
Could you tell me why you decided not to let components create event streams themselves? Is there any benefits?

**Comment by davesnx** [comment]
In a parent component you can create there the streams and pass it into a different components, basically.

**Comment by davesnx** [comment]
For use the "model" in different componets.

**Comment by jas-chen** [comment]
I don't think components will have same events to share (in your counter example you created 4 click event streams), but developers have to create event streams every time, that will cost lots of time!

**Comment by davesnx** [comment]
In this case are events that are onClicks, but eventually I want to pass streams$ that have some data from the store. 

You are right, we need to differenciate the events$ of the components and the streams$ that comes from the store in some way. I will iterate on that.

**Comment by jas-chen** [comment]
Okay, keep going! :rocket:

**Comment by davesnx** [comment]
Do you prefer to have a chat, instead of discuss in this issue :[
Like in #reactiflux or something?

**Comment by jas-chen** [comment]
@davesnx I just sent you a message on gitter.
